# Generated by Django 4.0.3 on 2022-03-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Загрузите картинку', null=True, upload_to='products/models/', verbose_name='Картинка')),
                ('image_size', models.ImageField(blank=True, help_text='Загрузите картинку', null=True, upload_to='products/sizes/', verbose_name='Картинка с размерами')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукция',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='ID Пользователя Телеграм')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='фамилия')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Биография')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
    ]
