# Generated by Django 4.0.3 on 2022-03-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroxin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='about',
            field=models.TextField(verbose_name='Описание применения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание типа продукции'),
        ),
    ]
