# Generated by Django 4.0.3 on 2022-03-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroxin', '0002_alter_product_about_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус обработки заявки'),
        ),
    ]
