# Generated by Django 4.0.3 on 2022-03-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroxin', '0003_alter_subscriber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Заметки'),
        ),
    ]
