# Generated by Django 4.0.3 on 2022-03-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iroxin', '0004_alter_subscriber_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='bio',
            new_name='notes',
        ),
    ]
