# Generated by Django 4.0.3 on 2022-03-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroxin', '0005_rename_bio_subscriber_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заметки'),
        ),
    ]
